var l;
if(!window.a){var u=function(){var b=window.self===window.top;this.w=(this.X=b)?0:null;this.D=this.g=!1;this.m=this.l=-1;this.W=1;this.f={};this.B=[];var c=chrome.runtime.connect({name:b?"top":"sub"});this.a=c;this.C=c.id||c.a||Math.ceil(2147483647*Math.random());c.onMessage.addListener(this.onMessage.bind(this));c.onDisconnect.addListener(this.H.bind(this));this.b(window,"scroll",this.U);this.b(window,"blur",this.P);this.b(window,"keydown",this.G,!0);this.b(window,"keyup",this.G,!0);this.b(window,"mousedown",
this.R,!0);this.b(window,"mouseup",this.S,!0);this.b(document,"beforeload",this.N,!0);this.b(document,"DOMContentLoaded",this.O);b&&this.b(window,"resize",this.T)};window.a=!0;"object"==typeof browser&&(chrome=browser);var y={16:!0,17:!0,18:!0,45:!0,46:!0},D=["VIDEO","AUDIO","OBJECT","EMBED"],E=new RegExp(atob("eXRwbGF5ZXJcLmNvbmZpZ1xzKj1ccypcew==")),F=new RegExp(atob("XCI/dmlkZW9EYXRhXCI/XHMqOlxzKlxbXHs=")),G=new RegExp(atob("InByb2dyZXNzaXZlIjpccypcWw=="));l=u.prototype;l.J=function(b,c,e,g){try{var d=
document.activeElement,m=d&&0<=D.indexOf(d.tagName)?d:null;m||(m=(d=document.elementFromPoint(this.l,this.m))&&0<=D.indexOf(d.tagName)?d:null);for(var n=0,p,q,r,h,k=0;k<D.length;k++){for(var f=document.getElementsByTagName(D[k]),x=0;x<f.length;x++)if(d=f[x],3!=k||"application/x-shockwave-flash"==d.type.toLowerCase()){var t=d.src||d.data;if(t&&(t==b||t==c)){p=d;break}if(!m&&!q)if(!t||t!=e&&t!=g){var v=d.clientWidth,w=d.clientHeight;if(v&&w){var z=d.getBoundingClientRect();if(!(0>=z.right+window.scrollX||
0>=z.bottom+window.scrollY)){var A=window.getComputedStyle(d);if(!A||"hidden"!=A.visibility){var B=v*w;B>n&&1.35*v>w&&v<3*w&&(n=B,r=d);h||(h=d)}}}}else q=d}if(p)break}b=p||m||q||r||h;if(!b)return null;if("EMBED"==b.tagName&&!b.clientWidth&&!b.clientHeight){var C=b.parentElement;"OBJECT"==C.tagName&&(b=C)}return this.j(b)}catch(H){}};l.I=function(b,c,e){try{for(var g=[],d,g=Array.prototype.concat.apply(g,document.getElementsByTagName("FRAME")),g=Array.prototype.concat.apply(g,document.getElementsByTagName("IFRAME")),
m=0;m<g.length;m++){var n=g[m];if(parseInt(n.getAttribute("__idm_frm__"))==b){d=n;break}if(!d){var p=n.src;!p||p!=c&&p!=e||(d=n)}}return this.j(d)}catch(q){}};l.v=function(){var b=window.devicePixelRatio,c=document.width,e=document.body.scrollWidth;c&&e&&(b=c==e?0:c/e);return b};l.s=function(b){try{var c=b.getBoundingClientRect(),e=Math.round(c.width),g=Math.round(c.height);if(15>e||15>g)return null;var d=document.documentElement,m=d.scrollHeight||d.clientHeight,n=Math.round(c.left)+b.clientLeft,
p=Math.round(c.top)+b.clientTop;return n>=(d.scrollWidth||d.clientWidth)||p>=m?null:{left:n,top:p,right:n+e,bottom:p+g,zoom:this.v()}}catch(q){}};l.u=function(){this.a.postMessage([21,window.location.href])};l.i=function(b){if(b){if(!this.Y){this.Y=!0;this.b(window,"message",this.V);var c=document.createElement("script");c.src=chrome.extension.getURL("document.js");c.onload=function(){c.parentNode.removeChild(c)};document.documentElement.appendChild(c)}window.setTimeout(function(){window.postMessage([1],
"/")},3E3)}else if("loading"==document.readyState)this.F=!0;else{this.F=!1;b=document.getElementsByTagName("SCRIPT");for(var e=0;e<b.length;e++){c=b[e];if(!c.src&&E.test(c.innerText)){b=this.c();b=[34,b,-1,c.outerHTML];this.a.postMessage(b);break}if(!c.src&&F.test(c.innerText)){b=this.c();b=[34,b,-2,c.outerHTML];this.a.postMessage(b);break}if(!c.src&&G.test(c.innerText)){b=this.c();b=[34,b,-2,c.outerHTML];this.a.postMessage(b);break}}}};l.V=function(b){var c=b.data;c instanceof Array&&b.origin==(document.origin||
location.origin)&&2==c[0]&&this.a.postMessage([34,c[1],-1,c[2]])};l.M=function(b){var c=b[2]||this.I(b[3],b[4],b[5]),e=c&&this.f[c],e=e&&this.s(e);this.a.postMessage([22,b[1],b[3],c,e])};l.L=function(b){var c=!b[2],e=b[2]||this.J(b[3],b[4],b[5],b[6]);b=[23,b[1],e,!1];var g=e&&this.f[e];if(g){var d=this.s(g);d&&(b[4]=d);c?(b[5]=g.tagName,b[6]=g.src||g.data,b[7]=this.c()):d||document.contains(g)||(b[3]=!0,delete this.f[e])}this.a.postMessage(b)};l.j=function(b){try{var c=parseInt(b.getAttribute("__idm_id__"));
c||(c=this.C<<10|this.W++,b.setAttribute("__idm_id__",c));this.f[c]=b;return c}catch(e){}};l.c=function(b){var c;try{c=window.top.document.title}catch(e){}if(c)if(c=c.replace(/[ \t\r\n\u25B6]+/g," ").trim(),b)this.a.postMessage([24,b,c]);else return c};l.h=function(b){if(!this.A){var c="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,function(b){return this[b]}.bind({"%H":"\\w\\-\u00a0-\ufeff","%T":"\\w\\-.+*()$!,%\u00a0-\ufeff",
"%Q":"^\\s\\[\\]{}()"}));this.A=new RegExp(c,"gi")}for(var e=[];c=this.A.exec(b);)e.push(c.shift());return e};l.o=function(b,c,e){var g=[],d={},m="",n="",p=!e,q;if(e&&(q=b.getSelection(),!q||q.isCollapsed))return g;var r=b.getElementsByTagName("A");if(r)for(var h=0;h<r.length;h++){var k=r[h];if(k&&(p||q.containsNode(k,!0))){var f=k.href;f&&!d[f]&&c.test(f)&&(d[f]=g.push([f,2,k.innerText||k.title]));e&&d[f]&&(m+=k.innerText,m+="\n")}}if(r=b.getElementsByTagName("AREA"))for(h=0;h<r.length;h++)(k=r[h])&&
(p||q.containsNode(k,!0))&&(f=k.href)&&!d[f]&&c.test(f)&&(d[f]=g.push([f,2,k.alt]));if(r=p&&b.getElementsByTagName("IFRAME"))for(h=0;h<r.length;h++)(k=r[h])&&(p||q.containsNode(k,!0))&&(f=k.src)&&!d[f]&&c.test(f)&&(d[f]=g.push([f,4]));if(h=e&&q.toString())for(k=this.h(h),m=this.h(m),h=0;h<k.length;h++)(f=k[h])&&!d[f]&&c.test(f)&&0>m.indexOf(f)&&(d[f]=g.push([f,1]));if(m=(p||!g.length)&&b.getElementsByTagName("IMG"))for(h=0;h<m.length;h++)(k=m[h])&&(p||q.containsNode(k,!0))&&((f=k.src)&&!d[f]&&c.test(f)&&
(d[f]=g.push([f,3,"<<<=IDMTRANSMITIMGPREFIX=>>>"+k.alt])),p&&k.onclick&&(n+=k.onclick,n+="\n"));if(b=p&&b.getElementsByTagName("SCRIPT")){for(h=0;h<b.length;h++)n+=b[h].innerText,n+="\n";for(n=this.h(n);n.length;)(f=n.shift())&&!d[f]&&c.test(f)&&(d[f]=g.push([f,5]))}return g};l.K=function(b,c){for(var e=this.o(document,b,c),g=document.getElementsByTagName("IFRAME"),d=Array.prototype.push,m=0;m<g.length;m++)try{var n=g[m],p=n.contentDocument;p&&!n.src&&d.apply(e,this.o(p,b,c))}catch(q){}return e};
l.G=function(b){y[b.keyCode]&&this.a.postMessage([31,b.keyCode,"keydown"==b.type])};l.R=function(b){this.D&&this.a.postMessage([28]);if(0==b.button){var c=b.view.getSelection();this.g=c&&c.isCollapsed;this.a.postMessage([32,b.button,!0])}};l.S=function(b){if(0==b.button&&(this.l=b.clientX,this.m=b.clientY,this.a.postMessage([32,b.button,!1]),this.g)){this.g=!1;var c=b.view.getSelection();c&&!c.isCollapsed&&this.a.postMessage([26,b.clientX,b.clientY,this.v()])}};l.P=function(){this.g=!1;this.a.postMessage([33])};
l.U=function(){this.a.postMessage([29])};l.T=function(b){b=b.target;this.a.postMessage([30,b.innerWidth,b.innerHeight])};l.N=function(b){var c=b.target,e=c.tagName;0<=D.indexOf(e)&&b.url&&(c=this.j(c),this.a.postMessage([25,c,e,b.url]))};l.O=function(){this.F&&this.i()};l.onMessage=function(b){switch(b[0]){case 11:var c=b[2];if(c){this.w=c;try{window.frameElement&&window.frameElement.setAttribute("__idm_frm__",c)}catch(g){}}b[3]&&this.u();b[4]&&this.i();break;case 17:b[1]&&this.u();b[2]&&this.i(!0);
break;case 12:var c=this.K(b[4]?new RegExp(b[4],"i"):null,b[2]),e=[27,b[1],this.w,c.length];b[3]||(e[4]=c,e[5]=window.location.href,this.X&&(e[6]=window.location.href,e[7]=document.title));this.a.postMessage(e);break;case 13:this.D=b[1];break;case 14:this.c(b[1]);break;case 15:this.L(b);break;case 16:this.M(b)}};l.b=function(b){var c=Array.prototype.slice.call(arguments);c[2]=c[2].bind(this);this.B.push(c);b.addEventListener.apply(b,c.slice(1))};l.H=function(){for(var b;b=this.B.shift();){var c=b.shift();
c.removeEventListener.apply(c,b)}this.a=this.C=null;window.a=!1};new u};
